# Data cleaning

## Loading & Rename

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

df=pd.read_csv("https://raw.githubusercontent.com/fazlyrabbi77/DataProcessing/master/real-estate.csv")

df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

## Renaming column with inplace

In [2]:
df.rename(columns={
    "NUM_BEDROOMS": "BEDROOMS",
    "NUM_BATH": "BATH"
}, inplace=True)
df.head()

           PID  ST_NUM    ST_NAME OWN_OCCUPIED BEDROOMS BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y        3    1  1000
1  100002000.0   197.0  LEXINGTON            N        3  1.5    --
2  100003000.0     NaN  LEXINGTON            N      NaN    1   850
3  100004000.0   201.0   BERKELEY           12        1  NaN   700
4          NaN   203.0   BERKELEY            Y        3    2  1600

## Check the None Value

In [3]:
df.isnull().values.any()

np.True_

In [4]:
df.isnull().values.sum()

np.int64(8)

## Showing the None values as per attribute

In [5]:
null_column=df.columns[df.isnull().any()]
df[null_column].isnull().sum()

PID             1
ST_NUM          2
OWN_OCCUPIED    1
BEDROOMS        2
BATH            1
SQ_FT           1
dtype: int64

In [6]:
print(df[df.isnull().any(axis=1)][null_column].head())

           PID  ST_NUM OWN_OCCUPIED BEDROOMS    BATH SQ_FT
2  100003000.0     NaN            N      NaN       1   850
3  100004000.0   201.0           12        1     NaN   700
4          NaN   203.0            Y        3       2  1600
5  100006000.0   207.0            Y      NaN       1   800
6  100007000.0     NaN          NaN        2  HURLEY   950

## None Value Handiling
### Filling null values with specific value

In [7]:
df.fillna({"PID": 100005000}, inplace=True)

df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3       1  1000
1  100002000.0   197.0   LEXINGTON            N        3     1.5    --
2  100003000.0     NaN   LEXINGTON            N      NaN       1   850
3  100004000.0   201.0    BERKELEY           12        1     NaN   700
4  100005000.0   203.0    BERKELEY            Y        3       2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN       1   800
6  100007000.0     NaN  WASHINGTON          NaN        2  HURLEY   950
7  100008000.0   213.0     TREMONT            Y        1       1   NaN
8  100009000.0   215.0     TREMONT            Y       na       2  1800

## Romeve the ROW or Column value

In [8]:
df.drop(["PID"],axis=1,inplace=False)

   ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0   104.0      PUTNAM            Y        3       1  1000
1   197.0   LEXINGTON            N        3     1.5    --
2     NaN   LEXINGTON            N      NaN       1   850
3   201.0    BERKELEY           12        1     NaN   700
4   203.0    BERKELEY            Y        3       2  1600
5   207.0    BERKELEY            Y      NaN       1   800
6     NaN  WASHINGTON          NaN        2  HURLEY   950
7   213.0     TREMONT            Y        1       1   NaN
8   215.0     TREMONT            Y       na       2  1800

In [9]:
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3       1  1000
1  100002000.0   197.0   LEXINGTON            N        3     1.5    --
2  100003000.0     NaN   LEXINGTON            N      NaN       1   850
3  100004000.0   201.0    BERKELEY           12        1     NaN   700
4  100005000.0   203.0    BERKELEY            Y        3       2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN       1   800
6  100007000.0     NaN  WASHINGTON          NaN        2  HURLEY   950
7  100008000.0   213.0     TREMONT            Y        1       1   NaN
8  100009000.0   215.0     TREMONT            Y       na       2  1800

In [10]:
df.drop([7,8],axis=0,inplace=False)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3       1  1000
1  100002000.0   197.0   LEXINGTON            N        3     1.5    --
2  100003000.0     NaN   LEXINGTON            N      NaN       1   850
3  100004000.0   201.0    BERKELEY           12        1     NaN   700
4  100005000.0   203.0    BERKELEY            Y        3       2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN       1   800
6  100007000.0     NaN  WASHINGTON          NaN        2  HURLEY   950

In [11]:
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3       1  1000
1  100002000.0   197.0   LEXINGTON            N        3     1.5    --
2  100003000.0     NaN   LEXINGTON            N      NaN       1   850
3  100004000.0   201.0    BERKELEY           12        1     NaN   700
4  100005000.0   203.0    BERKELEY            Y        3       2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN       1   800
6  100007000.0     NaN  WASHINGTON          NaN        2  HURLEY   950
7  100008000.0   213.0     TREMONT            Y        1       1   NaN
8  100009000.0   215.0     TREMONT            Y       na       2  1800

## Row Wise data Filling

In [12]:
df.loc[2,"ST_NUM"]=197
df.loc[6,"ST_NUM"]=208
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3       1  1000
1  100002000.0   197.0   LEXINGTON            N        3     1.5    --
2  100003000.0   197.0   LEXINGTON            N      NaN       1   850
3  100004000.0   201.0    BERKELEY           12        1     NaN   700
4  100005000.0   203.0    BERKELEY            Y        3       2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN       1   800
6  100007000.0   208.0  WASHINGTON          NaN        2  HURLEY   950
7  100008000.0   213.0     TREMONT            Y        1       1   NaN
8  100009000.0   215.0     TREMONT            Y       na       2  1800

## Unwanted Value treatment

In [13]:
cnt=0
for row in df["OWN_OCCUPIED"]:
    try:
        int(row)
        df.loc[cnt, "OWN_OCCUPIED"]=np.nan
    except ValueError:
        pass
    cnt+=1


df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS    BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3       1  1000
1  100002000.0   197.0   LEXINGTON            N        3     1.5    --
2  100003000.0   197.0   LEXINGTON            N      NaN       1   850
3  100004000.0   201.0    BERKELEY          NaN        1     NaN   700
4  100005000.0   203.0    BERKELEY            Y        3       2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN       1   800
6  100007000.0   208.0  WASHINGTON          NaN        2  HURLEY   950
7  100008000.0   213.0     TREMONT            Y        1       1   NaN
8  100009000.0   215.0     TREMONT            Y       na       2  1800

In [14]:
cnt=0
for row in df["BATH"]:
    try:
        float(row)
        
    except ValueError:
        df.loc[cnt,"BATH"]=np.nan
    
    cnt+=1
    
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED BEDROOMS BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y        3    1  1000
1  100002000.0   197.0   LEXINGTON            N        3  1.5    --
2  100003000.0   197.0   LEXINGTON            N      NaN    1   850
3  100004000.0   201.0    BERKELEY          NaN        1  NaN   700
4  100005000.0   203.0    BERKELEY            Y        3    2  1600
5  100006000.0   207.0    BERKELEY            Y      NaN    1   800
6  100007000.0   208.0  WASHINGTON          NaN        2  NaN   950
7  100008000.0   213.0     TREMONT            Y        1    1   NaN
8  100009000.0   215.0     TREMONT            Y       na    2  1800

In [15]:
df["BEDROOMS"]=pd.to_numeric(df["BEDROOMS"],errors="coerce")
df["BATH"]=pd.to_numeric(df["BATH"],errors="coerce")
df["SQ_FT"]=pd.to_numeric(df["SQ_FT"],errors="coerce")
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y       3.0   1.0  1000.0
1  100002000.0   197.0   LEXINGTON            N       3.0   1.5     NaN
2  100003000.0   197.0   LEXINGTON            N       NaN   1.0   850.0
3  100004000.0   201.0    BERKELEY          NaN       1.0   NaN   700.0
4  100005000.0   203.0    BERKELEY            Y       3.0   2.0  1600.0
5  100006000.0   207.0    BERKELEY            Y       NaN   1.0   800.0
6  100007000.0   208.0  WASHINGTON          NaN       2.0   NaN   950.0
7  100008000.0   213.0     TREMONT            Y       1.0   1.0     NaN
8  100009000.0   215.0     TREMONT            Y       NaN   2.0  1800.0

## fiill the None value By MODE Value

In [16]:
df["OWN_OCCUPIED"] = df["OWN_OCCUPIED"].fillna(
    df["OWN_OCCUPIED"].mode()[0]
)

In [17]:
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y       3.0   1.0  1000.0
1  100002000.0   197.0   LEXINGTON            N       3.0   1.5     NaN
2  100003000.0   197.0   LEXINGTON            N       NaN   1.0   850.0
3  100004000.0   201.0    BERKELEY            Y       1.0   NaN   700.0
4  100005000.0   203.0    BERKELEY            Y       3.0   2.0  1600.0
5  100006000.0   207.0    BERKELEY            Y       NaN   1.0   800.0
6  100007000.0   208.0  WASHINGTON            Y       2.0   NaN   950.0
7  100008000.0   213.0     TREMONT            Y       1.0   1.0     NaN
8  100009000.0   215.0     TREMONT            Y       NaN   2.0  1800.0

## Use of Median
### Group by permeter check

In [18]:
df.groupby("BEDROOMS")["SQ_FT"].median()

BEDROOMS
1.0     700.0
2.0     950.0
3.0    1300.0
Name: SQ_FT, dtype: float64

## Filling Null with group by VParameter

In [19]:
df["SQ_FT"]=df["SQ_FT"].fillna(df.groupby("BEDROOMS")["SQ_FT"].transform("median"))
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y       3.0   1.0  1000.0
1  100002000.0   197.0   LEXINGTON            N       3.0   1.5  1300.0
2  100003000.0   197.0   LEXINGTON            N       NaN   1.0   850.0
3  100004000.0   201.0    BERKELEY            Y       1.0   NaN   700.0
4  100005000.0   203.0    BERKELEY            Y       3.0   2.0  1600.0
5  100006000.0   207.0    BERKELEY            Y       NaN   1.0   800.0
6  100007000.0   208.0  WASHINGTON            Y       2.0   NaN   950.0
7  100008000.0   213.0     TREMONT            Y       1.0   1.0   700.0
8  100009000.0   215.0     TREMONT            Y       NaN   2.0  1800.0

In [20]:
df["SQ_FT"]=df["SQ_FT"].fillna(df["SQ_FT"].median())

In [21]:
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y       3.0   1.0  1000.0
1  100002000.0   197.0   LEXINGTON            N       3.0   1.5  1300.0
2  100003000.0   197.0   LEXINGTON            N       NaN   1.0   850.0
3  100004000.0   201.0    BERKELEY            Y       1.0   NaN   700.0
4  100005000.0   203.0    BERKELEY            Y       3.0   2.0  1600.0
5  100006000.0   207.0    BERKELEY            Y       NaN   1.0   800.0
6  100007000.0   208.0  WASHINGTON            Y       2.0   NaN   950.0
7  100008000.0   213.0     TREMONT            Y       1.0   1.0   700.0
8  100009000.0   215.0     TREMONT            Y       NaN   2.0  1800.0

In [22]:
df.loc[8,"BEDROOMS"]=3
df.loc[2,"BEDROOMS"]=1
df.loc[5,"BEDROOMS"]=1

In [23]:
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y       3.0   1.0  1000.0
1  100002000.0   197.0   LEXINGTON            N       3.0   1.5  1300.0
2  100003000.0   197.0   LEXINGTON            N       1.0   1.0   850.0
3  100004000.0   201.0    BERKELEY            Y       1.0   NaN   700.0
4  100005000.0   203.0    BERKELEY            Y       3.0   2.0  1600.0
5  100006000.0   207.0    BERKELEY            Y       1.0   1.0   800.0
6  100007000.0   208.0  WASHINGTON            Y       2.0   NaN   950.0
7  100008000.0   213.0     TREMONT            Y       1.0   1.0   700.0
8  100009000.0   215.0     TREMONT            Y       3.0   2.0  1800.0

In [24]:
df["BATH"]=df["BATH"].bfill()
df

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y       3.0   1.0  1000.0
1  100002000.0   197.0   LEXINGTON            N       3.0   1.5  1300.0
2  100003000.0   197.0   LEXINGTON            N       1.0   1.0   850.0
3  100004000.0   201.0    BERKELEY            Y       1.0   2.0   700.0
4  100005000.0   203.0    BERKELEY            Y       3.0   2.0  1600.0
5  100006000.0   207.0    BERKELEY            Y       1.0   1.0   800.0
6  100007000.0   208.0  WASHINGTON            Y       2.0   1.0   950.0
7  100008000.0   213.0     TREMONT            Y       1.0   1.0   700.0
8  100009000.0   215.0     TREMONT            Y       3.0   2.0  1800.0

## converting street number to  int

In [25]:
df.PID=df.PID.astype("int64")
df.ST_NUM=df.ST_NUM.astype("int64")
df.BEDROOMS=df.BEDROOMS.astype("int64")
df.BATH=df.BATH.astype("int64")
df.SQ_FT=df.SQ_FT.astype("int64")

In [26]:
df

         PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH  SQ_FT
0  100001000     104      PUTNAM            Y         3     1   1000
1  100002000     197   LEXINGTON            N         3     1   1300
2  100003000     197   LEXINGTON            N         1     1    850
3  100004000     201    BERKELEY            Y         1     2    700
4  100005000     203    BERKELEY            Y         3     2   1600
5  100006000     207    BERKELEY            Y         1     1    800
6  100007000     208  WASHINGTON            Y         2     1    950
7  100008000     213     TREMONT            Y         1     1    700
8  100009000     215     TREMONT            Y         3     2   1800

In [27]:
df.dropna()

         PID  ST_NUM     ST_NAME OWN_OCCUPIED  BEDROOMS  BATH  SQ_FT
0  100001000     104      PUTNAM            Y         3     1   1000
1  100002000     197   LEXINGTON            N         3     1   1300
2  100003000     197   LEXINGTON            N         1     1    850
3  100004000     201    BERKELEY            Y         1     2    700
4  100005000     203    BERKELEY            Y         3     2   1600
5  100006000     207    BERKELEY            Y         1     1    800
6  100007000     208  WASHINGTON            Y         2     1    950
7  100008000     213     TREMONT            Y         1     1    700
8  100009000     215     TREMONT            Y         3     2   1800